---
- name: SYSTEM | Install basic database packages
  package: name={{ item }} state=present
  with_items:
    - postgresql
    - postgresql-contrib
    - python-psycopg2

- name: POSTGRES | Create mattermost database
  become: true
  become_user: postgres
  postgresql_db:
    name: mattermost

- name: POSTGRES | Create mattermost DB user
  become: yes
  become_user: postgres
  postgresql_user:
    db: mattermost
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: ALL

- name: POSTGRES | Shore up DB privileges for our application user
  become: yes
  become_user: postgres
  postgresql_user: 
    name: "{{ db_user }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB


- block:
  - name: POSTGRES | Set up pg_hba.conf, allow connections from webservers
    template: src=pg_hba.conf dest={{ PG_HBA_CONF }}
    notify:
      - restart postgres

  - name: POSTGRES | Listen on all IPs
    lineinfile:
      dest: "{{ PG_CONF }}"
      line: listen_addresses='*'
    notify:
      - restart postgres
  # we only open up Postgres if we're running a separate web server
  when: hostvars[groups['webservers'][0]]['inventory_hostname'] != inventory_hostname
